"""Facade di compatibilita` per il vecchio layer dati.

Il progetto sta migrando verso i moduli in `repositories/`.
Questo file mantiene l'API storica per evitare rotture durante il refactor.
"""

from repositories.backup_repository import (
    drop_all_backup_tables,
    get_all_backups,
    restore_macro_from_backup,
)
from repositories.database import (
    connect_db,
    get_db_path,
    setup_backup_table,
    setup_game_elements_table,
    setup_main_table,
    setup_scheduled_tasks_table,
    setup_task_macro_sequence_table,
)
from repositories.game_element_repository import (
    create_game_element,
    delete_game_element,
    get_all_game_elements,
    get_game_element_by_id,
    update_game_element,
)
from repositories.macro_repository import (
    delete_macro,
    duplicate_macro,
    get_all_macros,
    get_macro_metadata_by_id,
    get_macro_metadata_by_name,
    load_macro_events,
    salva_macro_test,
    update_macro_events_only,
    update_macro_full,
)
from repositories.task_repository import (
    add_macro_to_task_sequence,
    add_macro_to_task_sequence_with_order,
    check_and_complete_task_if_needed,
    clear_task_macro_sequence,
    create_scheduled_task,
    delete_scheduled_task,
    duplicate_scheduled_task,
    get_active_tasks_ordered_by_next_execution,
    get_all_scheduled_tasks,
    get_scheduled_task_by_id,
    get_task_macro_sequence,
    get_tasks_due_for_execution,
    increment_task_execution_count,
    reactivate_completed_task,
    remove_macro_from_task_sequence,
    start_task_scheduling,
    stop_task_scheduling,
    update_last_execution,
    update_macro_sequence_wait_time,
    update_scheduled_task,
)

__all__ = [
    "add_macro_to_task_sequence",
    "add_macro_to_task_sequence_with_order",
    "check_and_complete_task_if_needed",
    "clear_task_macro_sequence",
    "connect_db",
    "create_game_element",
    "create_scheduled_task",
    "delete_game_element",
    "delete_macro",
    "delete_scheduled_task",
    "drop_all_backup_tables",
    "duplicate_macro",
    "duplicate_scheduled_task",
    "get_active_tasks_ordered_by_next_execution",
    "get_all_backups",
    "get_all_game_elements",
    "get_all_macros",
    "get_all_scheduled_tasks",
    "get_db_path",
    "get_game_element_by_id",
    "get_macro_metadata_by_id",
    "get_macro_metadata_by_name",
    "get_scheduled_task_by_id",
    "get_task_macro_sequence",
    "get_tasks_due_for_execution",
    "increment_task_execution_count",
    "load_macro_events",
    "reactivate_completed_task",
    "remove_macro_from_task_sequence",
    "restore_macro_from_backup",
    "salva_macro_test",
    "setup_backup_table",
    "setup_game_elements_table",
    "setup_main_table",
    "setup_scheduled_tasks_table",
    "setup_task_macro_sequence_table",
    "start_task_scheduling",
    "stop_task_scheduling",
    "update_game_element",
    "update_last_execution",
    "update_macro_events_only",
    "update_macro_full",
    "update_macro_sequence_wait_time",
    "update_scheduled_task",
]
